using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Prototypes;
using Content.Shared._Arcane.ErpPanel;
using System.Linq;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Content.Client.Stylesheets;
using Robust.Client.GameObjects;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Arcane.ErpPanel;

[GenerateTypedNameReferences]
public sealed partial class ErpPanelWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly SpriteSystem _sprite;

    private static readonly Color BackgroundColor = new Color(21, 29, 33);
    private static readonly Color FrameColor = new Color(50, 80, 99);
    private static readonly Color ButtonColor = new Color(85, 133, 138);
    private static readonly Color ButtonFrameColor = new Color(99, 235, 255);

    private HashSet<string> _openedCategories = new();
    private TimeSpan _lastUpdate = TimeSpan.Zero;
    private static readonly TimeSpan ReloadCooldown = TimeSpan.FromMilliseconds(250);

    private EntityUid? _currentUser;
    private EntityUid? _currentTarget;
    private List<string> _currentInteractions = new();

    public Action<string>? OnSendEmote;

    public ErpPanelWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();
    }

    public void SetTarget(NetEntity user, NetEntity target)
    {
        _currentUser = _entManager.GetEntity(user);
        _currentTarget = _entManager.GetEntity(target);
        _currentInteractions.Clear();
        ReloadInteractionsIfNeeded(true);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!IsOpen)
            return;

        ReloadInteractionsIfNeeded();
    }

    private void ReloadInteractionsIfNeeded(bool force = false)
    {
        if (!_currentUser.HasValue || !_currentTarget.HasValue)
            return;

        var now = _timing.CurTime;
        if (!force && now < _lastUpdate + ReloadCooldown)
            return;

        _lastUpdate = now;

        if (!TryUpdateCurrentInteractions())
            return;

        ReloadInteractions(_currentUser.Value, _currentTarget.Value);
    }

    private bool TryUpdateCurrentInteractions()
    {
        if (!_currentUser.HasValue || !_currentTarget.HasValue)
            return false;

        var user = _currentUser.Value;
        var target = _currentTarget.Value;

        var interactions = _prototypeManager.EnumeratePrototypes<PanelInteractionPrototype>();

        var newInteractions = new List<string>();
        foreach (var interaction in interactions)
        {
            var requirementPassed = CheckRequirements(user, target, interaction);
            if (!requirementPassed)
                continue;

            newInteractions.Add(interaction.ID);
        }

        newInteractions.Sort();

        // В Count мало смысла, но оптимизацию малость повысит.
        if (_currentInteractions.Count == newInteractions.Count && _currentInteractions.SequenceEqual(newInteractions))
        {
            return false;
        }

        _currentInteractions = newInteractions;
        return true;
    }

    private void ReloadInteractions(EntityUid user, EntityUid target)
    {
        ButtonsContainer.DisposeAllChildren();

        var categories = _prototypeManager.EnumeratePrototypes<PanelInteractionCategoryPrototype>();
        var interactions = _prototypeManager.EnumeratePrototypes<PanelInteractionPrototype>();

        foreach (var category in categories)
        {
            var categoryCollapsible = PrepareInteractionCategory(category);
            ButtonsContainer.AddChild(categoryCollapsible);

            var categoryBody = new BoxContainer() { Orientation = LayoutOrientation.Vertical };
            categoryCollapsible.Body?.AddChild(categoryBody);

            foreach (var interaction in interactions.Where(i => i.Category.Id == category.ID))
            {
                var requirementPassed = CheckRequirements(user, target, interaction);
                if (!requirementPassed)
                    continue;

                var interactionContainer = PrepareInteractionButton(interaction);
                categoryBody.AddChild(interactionContainer);
            }
        }
    }

    private Collapsible PrepareInteractionCategory(PanelInteractionCategoryPrototype categoryProto)
    {
        var heading = new CollapsibleHeading(categoryProto.Name)
        {
            ChevronMargin = new Thickness(10, 0),
            MinHeight = 32,
        };

        heading.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = BackgroundColor,
            BorderColor = FrameColor,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        var body = new CollapsibleBody();

        var category = new Collapsible(heading, body)
        {
            HorizontalExpand = true
        };

        heading.OnPressed += _ =>
        {
            category.BodyVisible = !category.BodyVisible;

            if (category.BodyVisible)
                _openedCategories.Add(categoryProto.Name);
            else
                _openedCategories.Remove(categoryProto.Name);
        };

        category.BodyVisible = _openedCategories.Contains(categoryProto.Name);

        return category;
    }

    private BoxContainer PrepareInteractionButton(PanelInteractionPrototype interaction)
    {
        var container = new BoxContainer();

        var button = new Button()
        {
            Text = interaction.Name,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 0),
            StyleClasses = { StyleBase.ButtonSquare },
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = ButtonColor,
                BorderColor = ButtonFrameColor,
                BorderThickness = new Thickness(2)
            }
        };

        button.OnPressed += _ => OnSendEmote?.Invoke(interaction.ID);

        var icon = new TextureRect()
        {
            Texture = _sprite.Frame0(interaction.Icon),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Left,
        };

        button.AddChild(icon);
        container.AddChild(button);

        return container;
    }

    private bool CheckRequirements(EntityUid user, EntityUid target, PanelInteractionPrototype interaction)
    {
        var passed = true;

        if (interaction.UserRequirements != null)
        {
            foreach (var requirement in interaction.UserRequirements)
            {
                if (!requirement.IsAvailable(user, _entManager))
                    passed = false;
            }
        }

        if (interaction.TargetRequirements != null)
        {
            foreach (var requirement in interaction.TargetRequirements)
            {
                if (!requirement.IsAvailable(target, _entManager))
                    passed = false;
            }
        }

        return passed;
    }
}
